apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: oficina
  labels:
    app.kubernetes.io/part-of: fiap-fase3
data:
  NODE_ENV: production
  PORT: "3000"
  AWS_REGION: us-east-1
  LOG_LEVEL: info
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  FRONTEND_URL: __FRONTEND_URL__
  SKIP_SECRETS_LOADER: "true"
  DB_SSL: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: __OTLP_ENDPOINT__
  OTEL_SERVICE_NAME: fiap-fase3-app
