apiVersion: batch/v1
kind: Job
metadata:
  name: api-migrations
  namespace: oficina
  labels:
    app: api-migrations
    app.kubernetes.io/part-of: fiap-fase3
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: __IMAGE__
          command: ["node", "dist/scripts/run-migrations.js"]
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
